### ISSUE TITLE
New-AMFileSystemCondition doesnt support the new PollingMode that was introduced in Automate 11.1.20.19 

### ISSUE THREAD

**Issue by sknijn** [automateps/AutomatePS#22]
See:
https://www.helpsystems.com/products/powerful-desktop-automation-tool/automate-version-history

[18512] A Polling mode has been added to the File Trigger to enhance reliability.

I added it in the code and tested; it works good.

## Specifications
  - AutoMatePS Version: newest
  - PowerShell Version: newest
  - AutoMate Enterprise Version: newest
[New-AMFileSystemCondition.zip](https://github.com/automateps/AutomatePS/files/3268283/New-AMFileSystemCondition.zip)

**Comment by davidseibel** [comment]
Good catch, thanks for sharing.  I'll put this in, although I'm making some slight changes:
- Naming parameter -UsePollingMode instead of -PollingMode - I typically like to name any switch parameter so that it's clear that it isn't a parameter that requires a value.
- Only allowing the -UsePollingMode parameter to change the PollingInterval property if the version is 11.1.20 or later.

In the future, please contribute changes by forking the repository and creating a pull request.
https://help.github.com/en/articles/about-collaborative-development-models
https://help.github.com/en/articles/creating-a-pull-request-from-a-fork
